# Generated by Django 3.2.6 on 2022-01-16 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your story.', max_length=300)),
                ('content', models.TextField(help_text='Describe the story.')),
                ('is_available', models.BooleanField(default=False, help_text='Is this for everyone.')),
                ('author', models.CharField(blank=True, help_text='Who is the owner of the story. This field is optional.', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(help_text='Who is publishing the story.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-date'],
            },
        ),
    ]
