# Generated by Django 4.0 on 2022-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
