# Generated by Django 3.2.6 on 2022-01-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What is the title?.', max_length=300)),
                ('content', models.TextField(help_text='Write the content.')),
                ('is_available', models.BooleanField(default=False, help_text='Is this for everyone.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text="The author's name.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tips',
                'ordering': ['-date'],
            },
        ),
    ]
