# Generated by Django 3.2.6 on 2022-01-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this for everyone.'),
        ),
    ]
